"""Compatibility facade for generic evidence-sufficiency contracts.

The canonical implementation lives in ``archflow.evidence.sufficiency``.
This module intentionally owns no implementation so existing imports preserve
class and function identity.
"""

from archflow.evidence.sufficiency import (
    ClosureStatus,
    ConflictDisposition,
    DecisionEdge,
    DecisionNode,
    DecisionUniverseClosure,
    DecisionUniverseRevision,
    DiscoverySweepReceipt,
    EpistemicRole,
    EvidenceClaimBinding,
    EvidenceModality,
    EvidenceRule,
    EvidenceSufficiencyError,
    EvidenceSufficiencyPolicy,
    EvidenceSufficiencyReceipt,
    ExpansionDisposition,
    ExpansionKind,
    FrontierStatus,
    FrontierWorkItem,
    Gap,
    GapReason,
    NumericUncertainty,
    ResearchFrontier,
    ResolutionMode,
    ResolutionRecord,
    SufficiencyStatus,
    TargetKind,
    UniverseExpansionCandidate,
    build_research_frontier,
    compile_decision_universe_closure,
    compile_evidence_sufficiency,
)

__all__ = [
    "ClosureStatus",
    "ConflictDisposition",
    "DecisionEdge",
    "DecisionNode",
    "DecisionUniverseClosure",
    "DecisionUniverseRevision",
    "DiscoverySweepReceipt",
    "EpistemicRole",
    "EvidenceClaimBinding",
    "EvidenceModality",
    "EvidenceRule",
    "EvidenceSufficiencyError",
    "EvidenceSufficiencyPolicy",
    "EvidenceSufficiencyReceipt",
    "ExpansionDisposition",
    "ExpansionKind",
    "FrontierStatus",
    "FrontierWorkItem",
    "Gap",
    "GapReason",
    "NumericUncertainty",
    "ResearchFrontier",
    "ResolutionMode",
    "ResolutionRecord",
    "SufficiencyStatus",
    "TargetKind",
    "UniverseExpansionCandidate",
    "build_research_frontier",
    "compile_decision_universe_closure",
    "compile_evidence_sufficiency",
]
