"""Stable public API for generic deterministic compilers."""

from archflow.compilers.geometry import (
    AssetSubstitutionReceipt,
    CompiledGeometryObject,
    CompiledGeometryProgram,
    GeometryCompilationError,
    GeometryCompilationReceipt,
    GeometryCompilationResult,
    GeometryCompileStatus,
    GeometryIssue,
    GeometryIssueCode,
    compile_geometry_program,
)
from archflow.compilers.program import (
    CompiledDesignProgram,
    ProgramAssumptionProposal,
    ProgramCompilationError,
    ProgramCompilationReceipt,
    ProgramMetricApplicabilityBinding,
    ProgramNodeProposal,
    ProgramProposalBundle,
    ProgramRangeProposal,
    ProgramRelationshipProposal,
    ProgramScenarioProposal,
    compile_design_program,
    maximum_footprint_constraint_refs,
)
from archflow.compilers.resources import (
    BuildAssumptionProposal,
    BuildBudgetProposal,
    BuildPolicyProposal,
    CompiledBuildPolicy,
    ConstructabilityConstraintProposal,
    ProtectedBlockRuleProposal,
    ResourceAvailabilityProposal,
    ResourceCompilationError,
    ResourceCompilationReceipt,
    ResourceDemandProposal,
    StagingAssumptionProposal,
    compile_build_policy,
)
from archflow.compilers.site import (
    CompiledSiteContext,
    SiteCompilationError,
    SiteCompilationReceipt,
    compile_site_context,
)
from archflow.compilers.voxel_program import compile_building_program

__all__ = [
    "AssetSubstitutionReceipt",
    "BuildAssumptionProposal",
    "BuildBudgetProposal",
    "BuildPolicyProposal",
    "CompiledBuildPolicy",
    "CompiledDesignProgram",
    "CompiledGeometryObject",
    "CompiledGeometryProgram",
    "CompiledSiteContext",
    "ConstructabilityConstraintProposal",
    "GeometryCompilationError",
    "GeometryCompilationReceipt",
    "GeometryCompilationResult",
    "GeometryCompileStatus",
    "GeometryIssue",
    "GeometryIssueCode",
    "ProgramAssumptionProposal",
    "ProgramCompilationError",
    "ProgramCompilationReceipt",
    "ProgramMetricApplicabilityBinding",
    "ProgramNodeProposal",
    "ProgramProposalBundle",
    "ProgramRangeProposal",
    "ProgramRelationshipProposal",
    "ProgramScenarioProposal",
    "ProtectedBlockRuleProposal",
    "ResourceAvailabilityProposal",
    "ResourceCompilationError",
    "ResourceCompilationReceipt",
    "ResourceDemandProposal",
    "SiteCompilationError",
    "SiteCompilationReceipt",
    "StagingAssumptionProposal",
    "compile_build_policy",
    "compile_building_program",
    "compile_design_program",
    "compile_geometry_program",
    "compile_site_context",
    "maximum_footprint_constraint_refs",
]
