"""Work registry: what is live, what is next, and the two generated ledgers.

The registry holds only work that is not finished. Finished work lives in Git
history; a card that is done is deleted together with its registry entry.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "governance" / "work_registry.json"
MAP_PATH = ROOT / "docs" / "DYNAMIC_MAP.md"
PLANNING_INDEX = ROOT / "docs" / "mapping" / "planning" / "INDEX.md"
MODULE_REGISTRY = ROOT / "governance" / "module_registry.json"
SYSTEM_MAP = ROOT / "docs" / "SYSTEM_MAP.md"
SEMANTIC_REGISTRY = ROOT / "docs" / "SEMANTIC_REGISTRY.md"
SCHEMA = "ArchFlowDevelopmentRegistry@2"
STATUSES = ("active", "ready", "blocked")


def load_registry() -> dict:
    data = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    if data.get("schema") != SCHEMA:
        raise SystemExit(f"unsupported registry schema: {data.get('schema')!r}")
    seen: set[str] = set()
    for item in data["items"]:
        if item["id"] in seen:
            raise SystemExit(f"duplicate item id {item['id']}")
        seen.add(item["id"])
        if item["status"] not in STATUSES:
            raise SystemExit(f"{item['id']}: status must be one of {STATUSES}")
        if not (ROOT / item["card"]).is_file():
            raise SystemExit(f"{item['id']}: missing card {item['card']}")
    return data


def is_ready(item: dict, live_ids: set[str]) -> bool:
    """Ready when no live item blocks it; ids not in the registry are finished."""

    return item["status"] == "ready" and not any(
        dep in live_ids for dep in item.get("depends_on", ())
    )


def render(data: dict) -> tuple[str, str]:
    items = data["items"]
    live_ids = {item["id"] for item in items}
    active = [i["id"] for i in items if i["status"] == "active"]
    ready = [i["id"] for i in items if is_ready(i, live_ids)]
    blocked = [i["id"] for i in items if i["status"] == "blocked" or (i["status"] == "ready" and i["id"] not in ready)]
    if active:
        nxt = f"finish active work: {', '.join(active)}"
    elif ready:
        nxt = f"claim one of: {', '.join(ready)}"
    else:
        nxt = "nothing is ready; decide what unblocks"
    rows = "\n".join(
        f"| {i['id']} | {i['status']} | {i['goal']} | [{i['id']}]({Path(i['card']).name}) |"
        for i in items
    )
    table = "| ID | Status | Goal | Card |\n| --- | --- | --- | --- |\n" + rows
    dyn = (
        "# ArchFlow V4 Dynamic Map\n\n"
        "> Generated by `python tools/devctl.py render-map` from `governance/work_registry.json`.\n"
        "> Architecture rationale is in [ARCHITECTURE.md](ARCHITECTURE.md); finished work is in Git history.\n\n"
        f"Phase: {data.get('phase', '')}\n\n"
        f"- active: {', '.join(active) or 'none'}\n"
        f"- ready: {', '.join(ready) or 'none'}\n"
        f"- blocked: {', '.join(blocked) or 'none'}\n"
        f"- next: {nxt}\n\n"
        "## Live work\n\n"
        + table.replace("](", "](mapping/planning/")
        + "\n"
    )
    plan = (
        "# Planning ledger\n\n> Generated from `governance/work_registry.json`.\n\n"
        + table
        + "\n\n[Back to RMPA](../README.md)\n"
    )
    return dyn, plan


def render_system_map() -> str | None:
    """The short view of the registry: who owns what, and what they refuse."""

    if not MODULE_REGISTRY.is_file():
        return None
    data = json.loads(MODULE_REGISTRY.read_text(encoding="utf-8"))
    tick = chr(96)
    lines = [
        "# ArchFlow system map",
        "",
        "> Generated by " + tick + "python tools/devctl.py render-map" + tick + " from " + tick + "governance/module_registry.json" + tick + ".",
        "> One owner per capability. Read this before the tree; read " + tick + "docs/CANONICAL_SPINE.md" + tick + " for why.",
        "",
    ]
    groups: dict[str, list[dict]] = {}
    for entry in data["modules"]:
        groups.setdefault(entry["module_id"].split(".")[0], []).append(entry)
    for group, entries in groups.items():
        lines += [f"## {group}", ""]
        for e in sorted(entries, key=lambda x: x["module_id"]):
            flag = "" if e.get("status") == "canonical" else f" ({e.get('status')})"
            lines.append(f"### {e['module_id']}{flag} — {tick}{e['owner_path']}{tick}")
            lines.append(e["purpose"])
            lines.append("- owns: " + "; ".join(e.get("owns", [])))
            if e.get("does_not_own"):
                lines.append("- does not own: " + "; ".join(e["does_not_own"]))
            if e.get("public_api"):
                lines.append("- api: " + ", ".join(tick + x + tick for x in e["public_api"]))
            if e.get("invariants"):
                lines.append("- invariants: " + "; ".join(e["invariants"]))
            lines.append("")
    return "\n".join(lines)


def render_semantic_registry() -> str:
    """Roles, conditions and the compound phrases that resolve to them."""

    from archflow.semantics.conditions import CONDITIONS
    from archflow.semantics.registry import COMPOUND_PHRASES
    from archflow.semantics.roles import ROLES

    tick = chr(96)
    lines = ["# Architectural semantic registry", "",
             "> Generated by " + tick + "python tools/devctl.py render-map" + tick + " from " + tick + "archflow/semantics/" + tick + ".",
             "> A record's semantic_kind must resolve here (ADR-006). Entity, role and condition are three things.", ""]
    for title, terms in (("Roles", ROLES), ("Conditions", CONDITIONS)):
        lines += [f"## {title}", "", "| id | meaning | aliases |", "| --- | --- | --- |"]
        lines += [f"| {tick}{t.id}{tick} | {t.meaning} | {', '.join(t.aliases)} |" for t in terms]
        lines.append("")
    lines += ["## Compound phrases (authored before the registry; resolve once)", "", "| phrase | roles | conditions |", "| --- | --- | --- |"]
    lines += [f"| {tick}{k}{tick} | {', '.join(v[0])} | {', '.join(v[1])} |" for k, v in COMPOUND_PHRASES.items()]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("status")
    sub.add_parser("next")
    sub.add_parser("render-map")
    args = parser.parse_args(argv)
    data = load_registry()
    if args.command == "status":
        for item in data["items"]:
            print(f"{item['id']:6s} {item['status']:8s} {item['goal'][:100]}")
    elif args.command == "next":
        live_ids = {i["id"] for i in data["items"]}
        for item in data["items"]:
            if item["status"] == "active" or is_ready(item, live_ids):
                print(f"{item['id']:6s} {item['status']}")
    else:
        dyn, plan = render(data)
        MAP_PATH.write_text(dyn, encoding="utf-8", newline="\n")
        PLANNING_INDEX.write_text(plan, encoding="utf-8", newline="\n")
        system_map = render_system_map()
        SEMANTIC_REGISTRY.write_text(render_semantic_registry(), encoding="utf-8", newline="\n")
        if system_map is not None:
            SYSTEM_MAP.write_text(system_map, encoding="utf-8", newline="\n")
        print(f"rendered {MAP_PATH.relative_to(ROOT)}, {PLANNING_INDEX.relative_to(ROOT)}" + (f" and {SYSTEM_MAP.relative_to(ROOT)}" if system_map else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
